### ISSUE TITLE
Stray rename field for resource allocation

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2132] opened 2021-01-26 09:52 UTC
![image.png](https://images.zenhubusercontent.com/5e188a7332969d45e20e5d13/c5431ac8-bb15-413e-857b-2bc0116c4aea)

Observed by Claudio. I have been unable to reproduce this issue locally.

**Comment by hschu12** [comment] 2021-04-08 11:51
Unable to reproduce. It is not even possibble to rename projects from this page.
Closing for now.

**Comment by DanThrane** [comment] 2021-04-12 07:22
See slack message.

**Closed** 2021-04-19 06:50 UTC
Labels: bug, frontend
