### ISSUE TITLE
Unauthorized when refreshing one of two interfaces open

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2611] opened 2021-08-13 07:06 UTC
Getting unauthorized in interface window when refreshing while having multiple interface jobs open in tabs. This is not a problem when having multiple tabs open of the same instace.

Reproduce: 
- Start two interactive jobs (e.g. Jupyter, R-studio etc.) 
- Open both interface windows
- attempt to refresh the first window => unauthorized
- second windows works fine and can still refresh.
If window of none functioning interface is closed and opened again, it works but now the other window cant refresh.

Tested in Firefox, Brace, Chrome, and safari

**Comment by DanThrane** [comment] 2021-08-13 07:16
Duplicate of #2610

**Closed by DanThrane** 2021-08-13 07:16 UTC
Labels: bug
