### ISSUE TITLE
Improve UCloud Admin page

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3349] opened 2022-03-16 08:55 UTC
LOW PRIORITY. If we at some point have some spare time

Create a page for ADMINs of UCloud to lookup info from DB (read only):

Search for user and get: Projects, Wallets, Runs?, Storage Stats?
Search for Project and get: Members, Group Structure?, Wallets, Runs, SubAllocations?
Wildcard search ("*QUERY*") for usernames to see if exisits

Create a page for ADMINS of UCloud to edit info in DB (Might only be user specific):
Reset of 2FA for users.

**Comment by hschu12** [comment] 2022-03-16 08:56
@emolinaro @FedericaLoVerso Anything that would be nice to have that have not already been mentioned?

**Comment by claudiopica** [comment] 2022-03-16 09:15
@hschu12 Not a good idea, if you mean direct edit in the DB.
If you have in mind an interface on the admin page that allows to update some info, then we can keep this open.

which one is?

**Comment by emolinaro** [comment] 2022-03-16 09:28
I think the main idea is to collect useful information from the database, not to change it.

**Comment by hschu12** [comment] 2022-03-16 09:28
All this should of course be in an safe interface on UClouds Admin page. Nothing should be direct access to the DB.

Most of the above is read only.
The only edit would be the reset of 2FA. This only sends the request to the backend which should resolve, check, and update/delete the relevant infomation in the DB.

**Comment by claudiopica** [comment] 2022-03-16 09:43
that sounds reasonable. We should change the name of the issue. it's kinda of scary...

**Comment by claudiopica** [comment] 2022-03-16 09:44
@emolinaro "collecting" data from the DB is not allowed. Also we use grafana for this.

**Comment by Tobias-V** [comment] 2022-03-22 16:25
A relevant query could be 'What were the last 10 runs [USER] submitted?' in combination with 'What were the parameters of the [RUN]'? 

A 'support' ticket about an app usually starts with us reproducing their issue, so we very often start by requesting additional information from the user about the run. It might take multiple e-mails back and forth to get this right, and if we're unable to reproduce their issue with this information, we might doubt the accuracy of it - this puts us in a situation where we have to ask the user to confirm that they sent us the right information - something I think we should strive to avoid.

Other relevant queries, as Henrik mentioned, could be about wallets, sub allocations etc.

The queries will either provide us with information we could and can ask the users for, or information we would ask Henrik for.

**Comment by Tobias-V** [comment] 2022-03-22 22:20
I think we agree - and I don't think it's necessary with the temporary solution you described, we want the ideal solution. We're not suggesting to grant read-only database access to support, but that support can see this information somewhere in UCloud.

**Comment by DanThrane** [comment] 2022-08-12 08:25
I'm closing this in favour of more focused issues. I know we have a meeting coming up to discuss some more concrete changes.

**Closed by DanThrane** 2022-08-12 08:25 UTC
Labels: enhancement, discussion, backend, frontend
