### ISSUE TITLE
App search does not show all apps

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3387] opened 2022-04-06 07:12 UTC
There is something off with the application search.

I am unable to find the 'Coder CUDA' app through searching, neither the keyword 'coder' nor 'cuda' finds it.

https://cloud.sdu.dk/app/applications/search?q=cuda

Apparently it does show up when an admin searches, but there should be a public version. Bug?

**Comment by claudiopica** [comment] 2022-04-06 07:14
It is a bug.
This is likely related to the fact that the "latest" version is a dev version not publicly available.

**Comment by Tobias-V** [comment] 2022-04-06 07:17
Just to be clear, I can browse applications and find this (public) version: https://cloud.sdu.dk/app/jobs/create?app=coder-cuda&version=1.48.2-1
It is only when searching it is not available.

**Comment by hschu12** [comment] 2022-04-07 12:02
@Tobias-V  You should be able to find the app now, but the issue is most likely still there.
It would seem that our search finds the latest version, however since the latest version at that time was a non public 1.64.2-dev you could not see it.

**Comment by DanThrane** [comment] 2022-04-11 11:08
Fix merged, not yet deployed (unless Henrik already did this).

**Closed by DanThrane** 2022-04-11 11:08 UTC
