### ISSUE TITLE
[storage] Browse files for upload does not work in Safari

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2007] opened 2020-11-25 09:30 UTC
When attempting to click browse to select files for upload nothing happens.
Reproducable on MacOS 10.14.6 with safari 14.0.1 (14610.2.11.51.10)

**Comment by Tiggles** [comment] 2021-02-11 08:36
Can't reproduce on MacOS 11.2, Safari 14.0.3

**Comment by Tiggles** [comment] 2021-03-15 15:00
Still works for me. Closing for now.

**Closed by Tiggles** 2021-03-15 15:00 UTC
Labels: bug, frontend, more info required
