### ISSUE TITLE
Create an input parameter which can use a list of files

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#3418] opened 2022-05-04 12:57 UTC
Some batch jobs can use multiple input files when running. It would be nice to have the possiblity to select multiple files in an input file parameter. Could be a list of files that also allows just a single element.

**Comment by DanThrane** [comment] 2022-05-04 13:10
I have changed the title since I believe this should be a new parameter which is explicitly mentioned in the application specification. While convenient to just have all apps work like this, I feel it will break quite a lot.

**Comment by Tiggles** [comment] 2024-06-04 10:45
Duplicate of #3632

**Closed by Tiggles** 2024-06-04 10:45 UTC
Labels: enhancement, Core: Backend, Core: Frontend
