### ISSUE TITLE
Mounting a drive (not folder in drive) will create a copy in output files for job

### ISSUE THREAD

**Issue by Tiggles** [SDU-eScience/UCloud#4260] opened 2024-06-12 14:39 UTC
- Run `terminal` with drive mounted (probably works for other apps)
- Stop app (or let it finish)
- A folder named after the drive has appeared in the output folder

**Comment by DanThrane** [comment] 2024-06-18 07:41
I am pretty sure this is a duplicate of #3953.

**Closed by DanThrane** 2024-06-18 07:41 UTC
Labels: bug, IM jobs: UCloud
