### ISSUE TITLE
Duplicate jobs on production

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2110] opened 2021-01-14 10:06 UTC
We see that jobs are submitted multiple times

**Comment by DanThrane** [comment] 2021-01-14 10:13
Appears to be caused by timeouts on production which leads to repeated requests from the frontend. I have temporarily increased timeouts for the production system.

**Comment by xiroV** [comment] 2021-01-15 08:25
Isn't this a duplicate of #2089 ?

**Closed** 2021-01-15 09:58 UTC
Labels: frontend, infrastructure, more info required
