### ISSUE TITLE
Issues with file upload conflict policy

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#4120] opened 2024-01-15 09:00 UTC
Some minor issues with file upload have been reported to Mads by a user. After a short investigation it seeems that:

 - The backend is not respecting the conflict policy defined by the frontend,
 - If the conflict policy is set to `REPLACE`, the existing file is not truncated properly.

**Comment by Tiggles** [comment] 2024-01-15 10:32
Duplicate of #3951. Closing the old one as this has better explanation

**Closed** 2024-01-30 09:03 UTC
