### ISSUE TITLE
Filter by "Created by" shows double of results if typing too fast

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#3110] opened 2021-12-08 15:30 UTC
I assume this happens when typing 2 letters in a row, with the second letter being typed before the results have refreshed after typing the first letter.

![image](https://user-images.githubusercontent.com/911284/145235189-4931e637-f5bf-46a7-9fbf-81c99f79da6e.png)

![image](https://user-images.githubusercontent.com/911284/145235317-d96deac9-46b9-40ec-a928-1ef811aa8bce.png)

**Comment by DanThrane** [comment] 2021-12-09 10:12
Duplicate of #2817

**Closed by DanThrane** 2021-12-09 10:12 UTC
