### ISSUE TITLE
Sorting drives by date or creator makes drives disappear

### ISSUE THREAD

**Issue by xiroV** [SDU-eScience/UCloud#2912] opened 2021-11-18 10:45 UTC
On dev

Reproduction:
 - Create 2 drives
 - Sort by "Date created" or "Created by"
 - The entries/drives will disappear until "Apply" is clicked.

Sort by "Name" does not seem to make the drives disappear.

Refreshing (without clicking "Apply") does not make the drives reappear.

**Comment by DanThrane** [comment] 2021-11-18 11:41
Duplicate of #2903

**Closed by DanThrane** 2021-11-18 11:41 UTC
Labels: bug, frontend
